version: '3'
 
services:
  app_1:
    image: webapp
    environment:
      - text=App1
    expose:
      - "5000"

  app_2:
    image: webapp
    environment:
      - text=App2
    expose:
      - "5000"

  app_3:
    image: webapp
    environment:
      - text=App3
    expose:
      - "5000"

  proxy:
    build:
      context:  ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    links:
      - app_1
      - app_2
      - app_3

